version: '3.7'

services:
  web:
    build:
      context: .
    image: web:local
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/application
    ports:
      - '3000:3000'
